-- ===============================================
-- Triggers for E-Commerce Order Management System
-- ===============================================

-- TRIGGER: Check if there is enough stock for the product
CREATE OR REPLACE TRIGGER check_stock_before_order
BEFORE INSERT ON OrderItems
FOR EACH ROW
DECLARE
    v_stock_qty NUMBER;
BEGIN
    SELECT StockQty INTO v_stock_qty FROM Products WHERE ProductID = :NEW.ProductID;
    IF :NEW.Quantity > v_stock_qty THEN
        RAISE_APPLICATION_ERROR(-20001, 'Not enough stock available for this product.');
    END IF;
    UPDATE Products SET StockQty = StockQty - :NEW.Quantity WHERE ProductID = :NEW.ProductID;
END;
/

-- TRIGGER: Auto-update stock after OrderItems insert
CREATE OR REPLACE TRIGGER trg_update_stock_after_order
AFTER INSERT ON OrderItems
FOR EACH ROW
BEGIN
    UPDATE Products
    SET StockQty = StockQty - :NEW.Quantity
    WHERE ProductID = :NEW.ProductID;
END;
/

CREATE TABLE Order_Cancellation_Log (
    LogID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    OrderID NUMBER,
    CancelledAt DATE DEFAULT SYSDATE,
    Reason VARCHAR2(200)
);

-- TRIGGER: Log cancelled orders
CREATE OR REPLACE TRIGGER trg_log_cancelled_order
AFTER UPDATE ON Orders
FOR EACH ROW
WHEN (OLD.Status != 'Cancelled' AND NEW.Status = 'Cancelled')
BEGIN
    INSERT INTO Order_Cancellation_Log (OrderID, Reason)
    VALUES (:OLD.OrderID, 'User Requested Cancellation');
END;
/